/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminLogin
 */
export interface AdminLogin {
  /**
   *
   * @type {string}
   * @memberof AdminLogin
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof AdminLogin
   */
  password: string;
}

/**
 * Check if a given object implements the AdminLogin interface.
 */
export function instanceOfAdminLogin(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "username" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function AdminLoginFromJSON(json: any): AdminLogin {
  return AdminLoginFromJSONTyped(json, false);
}

export function AdminLoginFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdminLogin {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json["username"],
    password: json["password"],
  };
}

export function AdminLoginToJSON(value?: AdminLogin | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    password: value.password,
  };
}
