/* tslint:disable */
/* eslint-disable */
/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCreate
 */
export interface AdminCreate {
  /**
   *
   * @type {number}
   * @memberof AdminCreate
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof AdminCreate
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof AdminCreate
   */
  password: string;
}

/**
 * Check if a given object implements the AdminCreate interface.
 */
export function instanceOfAdminCreate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "username" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function AdminCreateFromJSON(json: any): AdminCreate {
  return AdminCreateFromJSONTyped(json, false);
}

export function AdminCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdminCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    username: json["username"],
    password: json["password"],
  };
}

export function AdminCreateToJSON(value?: AdminCreate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    username: value.username,
    password: value.password,
  };
}
