/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Admin
 */
export interface Admin {
  /**
   *
   * @type {number}
   * @memberof Admin
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Admin
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof Admin
   */
  salt: string;
  /**
   *
   * @type {string}
   * @memberof Admin
   */
  password: string;
}

/**
 * Check if a given object implements the Admin interface.
 */
export function instanceOfAdmin(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "username" in value;
  isInstance = isInstance && "salt" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function AdminFromJSON(json: any): Admin {
  return AdminFromJSONTyped(json, false);
}

export function AdminFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Admin {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    username: json["username"],
    salt: json["salt"],
    password: json["password"],
  };
}

export function AdminToJSON(value?: Admin | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    username: value.username,
    salt: value.salt,
    password: value.password,
  };
}
