/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Department } from "../models";
import { DepartmentFromJSON, DepartmentToJSON } from "../models";

/**
 *
 */
export class DepartmentsApi extends runtime.BaseAPI {
  /**
   * Get list of departments
   * Get Departments List
   */
  async getDepartmentsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Department>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/users/get_departments`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(DepartmentFromJSON)
    );
  }

  /**
   * Get list of departments
   * Get Departments List
   */
  async getDepartments(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Department>> {
    const response = await this.getDepartmentsRaw(initOverrides);
    return await response.value();
  }
}
