/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  HTTPValidationError,
  PatientCreate,
  PatientInDB,
} from "../models";
import {
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  PatientCreateFromJSON,
  PatientCreateToJSON,
  PatientInDBFromJSON,
  PatientInDBToJSON,
} from "../models";

import { UpdatePatientRequest } from "./UpdateApi";

/**
 *
 */
export class PatientsApi extends runtime.BaseAPI {
  /**
   * Update patient details
   * Update Patient
   */
  async updatePatientRaw(
    requestParameters: UpdatePatientRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PatientInDB>> {
    if (
      requestParameters.patientCreate === null ||
      requestParameters.patientCreate === undefined
    ) {
      throw new runtime.RequiredError(
        "patientCreate",
        "Required parameter requestParameters.patientCreate was null or undefined when calling updatePatient."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/users/update_patient`,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: PatientCreateToJSON(requestParameters.patientCreate),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PatientInDBFromJSON(jsonValue)
    );
  }

  /**
   * Update patient details
   * Update Patient
   */
  async updatePatient(
    requestParameters: UpdatePatientRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PatientInDB> {
    const response = await this.updatePatientRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
