/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Schedule,
} from '../models';
import {
    ScheduleFromJSON,
    ScheduleToJSON,
} from '../models';

/**
 * 
 */
export class SchedulesApi extends runtime.BaseAPI {

    /**
     * Get list of schedules
     * Get Chedules List
     */
    async getSchedulesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Schedule>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/get_schedules`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScheduleFromJSON));
    }

    /**
     * Get list of schedules
     * Get Chedules List
     */
    async getSchedules(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Schedule>> {
        const response = await this.getSchedulesRaw(initOverrides);
        return await response.value();
    }

}
