/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Schedule,
} from '../models';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ScheduleFromJSON,
    ScheduleToJSON,
} from '../models';

export interface CreateScheduleRequest {
    schedule: Schedule;
}

/**
 * 
 */
export class ScheduleRegistrationApi extends runtime.BaseAPI {

    /**
     * Register new schedule
     * Department Create
     */
    async createScheduleRaw(requestParameters: CreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Schedule>> {
        if (requestParameters.schedule === null || requestParameters.schedule === undefined) {
            throw new runtime.RequiredError('schedule','Required parameter requestParameters.schedule was null or undefined when calling createSchedule.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/create_schedule`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleToJSON(requestParameters.schedule),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleFromJSON(jsonValue));
    }

    /**
     * Register new schedule
     * Department Create
     */
    async createSchedule(requestParameters: CreateScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Schedule> {
        const response = await this.createScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
