/* tslint:disable */
/* eslint-disable */
/**
 * densys
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PatientPublic,
} from '../models';
import {
    PatientPublicFromJSON,
    PatientPublicToJSON,
} from '../models';

/**
 * 
 */
export class TestApi extends runtime.BaseAPI {

    /**
     * Get list of all patients
     * Get Patients
     */
    async getPatientsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PatientPublic>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/get_patients`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PatientPublicFromJSON));
    }

    /**
     * Get list of all patients
     * Get Patients
     */
    async getPatients(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PatientPublic>> {
        const response = await this.getPatientsRaw(initOverrides);
        return await response.value();
    }

}
